version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: db_statup
    restart: unless-stopped
    environment:
      - POSTGRES_DB=startup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
